# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82929377494d3fc0faf3fd9970467accd4161448a6df500114f0818ea33ed1fa9e45bf3fe79e035c800b0e5a6ec6aa3e70aac8c5f85454dd55571f9db3169d31

test:
  secret_key_base: c091595696eefa2b6fa347f55b3c77839271f2d7074cd0a3128ef120f2efbd3599d5b10629f8311d25bb6979ae4dceb2ababe640a4a84806e735761ef3f1b8c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
